##
# Pterodactyl Panel Docker Setup by ccarney
##
version: '2.1'
services:
##
# MariaDB (MySQL) Server
# If you rely on another MySQL/MariaDB instance, 
# this can be safely removed. If you want to have 
# your game servers be able to access this, be sure 
# to declare your ports.
##
  mysql:
    env_file: .env
    image: mariadb:10.4
    restart: always
    volumes:
    - ./db:/var/lib/mysql

# Panel Cache
# This service is required for the panel to function.
# You can use either redis or memcached, but redis
# is provided by default here.
##
  cache:
    image: redis:alpine
    restart: always

##
# Pterodactyl Panel
# This is the main service that will be seen publically.
##
  panel:
    depends_on:
    - cache
    - mysql
    env_file: .env
    image: docker.pkg.github.com/drschlaubi/pterodactyl-alpha-docker/pterodactyl-panel:v0.8.0-alpha.1
    restart: always
    volumes:
    - ./data:/data
    ports:
    - ${HTTP_PORT}:80
    - ${HTTPS_PORT}:443

##
# Wings - Pterodactyl Daemon
# If you don't plan on running the daemon on the same machine, 
# you may comment/delete the section below.
##
  wings:
    depends_on:
    - panel
    image: docker.pkg.github.com/drschlaubi/pterodactyl-alpha-docker/pterodactyl-wings:v1.0.0-alpha.1
    ports:
    -  ${WINGS_PORT}:8080
    privileged: true
    restart: always
    volumes:
    - /srv/wings/config.yml:/srv/wings/config.yml
    - /srv/wings/data/servers:/srv/wings/data/servers/
    - /srv/daemon-data/:/srv/daemon-data/

    - /tmp/pterodactyl:/tmp/pterodactyl

    - /etc/localtime:/etc/localtime

    # Docker socket and directory, needed to communicate to docker
    # NOTE: If you are using docker in a different directory, please change below to reflect that!
    - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
    - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
